CREATE TABLE public.cash_movements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movement_type text NOT NULL,
  amount numeric NOT NULL,
  movement_date timestamptz NOT NULL DEFAULT now(),
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT cash_movements_type_check
    CHECK (
      movement_type IN (
        'OWNER_CASH_IN',
        'OWNER_CASH_OUT',
        'CASH_ADJUSTMENT'
      )
    ),

  CONSTRAINT cash_movements_amount_check
    CHECK (
      (
        movement_type IN (
          'OWNER_CASH_IN',
          'OWNER_CASH_OUT'
        )
        AND amount > 0
      )
      OR (
        movement_type = 'CASH_ADJUSTMENT'
        AND amount <> 0
      )
    )
);

ALTER TABLE public.cash_movements
  ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON public.cash_movements
  TO authenticated;

CREATE POLICY "Admins can view cash movements"
  ON public.cash_movements
  FOR SELECT
  TO authenticated
  USING (
    public.current_user_role() = 'ADMIN'
  );

CREATE POLICY "Admins can insert cash movements"
  ON public.cash_movements
  FOR INSERT
  TO authenticated
  WITH CHECK (
    public.current_user_role() = 'ADMIN'
  );

CREATE POLICY "Admins can update cash movements"
  ON public.cash_movements
  FOR UPDATE
  TO authenticated
  USING (
    public.current_user_role() = 'ADMIN'
  )
  WITH CHECK (
    public.current_user_role() = 'ADMIN'
  );

CREATE POLICY "Admins can delete cash movements"
  ON public.cash_movements
  FOR DELETE
  TO authenticated
  USING (
    public.current_user_role() = 'ADMIN'
  );
